title: Easy vegan Wednesdays
description: >-
  Every other Wednesday at 18:30 live cooking on YouTube!
baseurl: ""
url: "https://evw.sernaleon.com"
theme: minima
show_excerpts: false
excerpt_separator: <!-- excerpt-end -->
future: true
plugins:
  - jekyll-feed
youtube_username: UCwBTVD1I9xWh_su95dGdVNA